### PR TITLE
Redirect to berlin.codefor.de/maps

### PR DESCRIPTION
**Pull request by tordans**
I find it confusing to have multiple pages whit the same content.

I suggest to deprecate this repo and redirect users to https://berlin.codefor.de/maps. This is what this PR does.

(Based on input at https://github.com/jochenklar/berlin-maps/pull/2#issuecomment-473846568.)

### CODE REVIEW

**Comment by jochenklar** [comment]
I would like to keep it as it is. This repo is a tiny, bare application to show any kin of tiles from a configuration which is not included. I use it now and then to set up test webpages.

**Comment by jochenklar** [comment]
I am thinking of moving https://github.com/jochenklar/berlin-maps/ and https://github.com/jochenklar/berlin-aerial/ to the codeforberlin orga.

**Comment by tordans** [comment]
I see, sounds good.
- Moving repos: Would the old links still work? That would be helpful.
- Keeping this as is: Are you open to a PR with a black link from the webpage to this repo and an updated readme that links to the other two repos? That would make it less confusing for me :)

**Comment by jochenklar** [comment]
* Links are redirected when you move repos.
* I can update the readme. What is a black link?

**Pull request closed without merging**
